### ISSUE TITLE
SNMPv3

### ISSUE THREAD

**Issue by ironbishop** [rsmuc/health_monitoring_plugins#10]
Is there any work going on for SNMPv3? What would be the best/fastest way to implement it?

**Comment by rsmuc** [comment]
Hi ironbishop,
currently we are not working on SNMPv3. In our systems there is currently no need to support that. In general it should be easy to implement, because the netsnmp python bindings seem to fully support SNMPv3. 

What plugin do you need?

**Comment by ironbishop** [comment]
I'm experimenting with IDRAC right now, and will probably use the ILO too. Speaking of which, is the ILO one just for version 4, or for all versions?

**Comment by rsmuc** [comment]
If I find some time I will try to implement SNMPv3 in the two plugins next week. Let's see how many effort that is...
The iDRAC plugin needs some bugfixes / changes anyway.

the iLo plugin will work for ilo 3 and 4. iLo 2 did not have a snmp interface for status monitoring. There is only a very slow xml interface to do that and e.g. the harddrive status is not shown via the xml interface. (But I think ilo 2 is obsolete anyway... HP Gen 5 was the last with ilo 2)

**Comment by ironbishop** [comment]
Thank you. Please let me know how it goes.

**Comment by rsmuc** [comment]
added also for the ilo plugin

**Comment by ironbishop** [comment]
Great!!! Thank you so much.
I'll test it asap.

**Comment by ironbishop** [comment]
It works, but it "breaks" previous versions checks: is that intentional, and v3 is now mandatory?

This worked before upgrade, but not now:
`[nagios@nserver ~]$ check_snmp_idrac.py -H ipaddress -V2 -C community`
`Unknown - security level is incorrect: None. Check -l parameter.`

I tried with v1 too:
`[nagios@nserver ~]$ check_snmp_idrac.py -H ipaddress -V 1 -C community`
`Unknown - security level is incorrect: None. Check -l parameter.`
And setting that parameter:
`[nagios@nserver ~]$ check_snmp_idrac.py -H ipaddress -V 2 -C community -l noAuthNoPriv`
`Unknown - snmpget failed - no data for host ipaddress OID: .1.3.6.1.4.1.674.10892.5.4.300.10.1.7.1`

Anyway, this is ok, and it's exactly what I need:
`[nagios@nserver ~]$ check_snmp_idrac.py -H ipaddress -V 3 -u user -a SHA -A password -x AES -X password -C community -l authPriv`
`OK ...`

**Comment by ironbishop** [comment]
Checked ILO too, it works.

`check_snmp_ilo4.py -H ipaddress -V 3 -u user -a SHA -A password -x AES -X password -l authPriv --driv
es=7 --ps=2 --fan=6`
