### ISSUE TITLE
Performance Data of check_snmp_raritan

### ISSUE THREAD

**Issue by crsprsp** [rsmuc/health_monitoring_plugins#15]
Hi, 

when i try to query a Raritan PDU, i get the following output: 

OK - Inlet. 4.173 A. 229.0 V. 818.0 W. 956.0 VA. 0.86. 427613.0 Wh. 49.9 Hz | 'Sensor 0'=4.173A;0.0:20.8;0.0:25.6;; 'Sensor 1'=229.0V;194.0:247.0;188.0:254.0;; 'Sensor 2'=818.0W;0.0:3250.0;0.0:3500.0;; 'Sensor 3'=956.0VA;0.0:0.0;0.0:0.0;; 'Sensor 4'=0.86;0.0:0.0;0.0:0.0;; 'Sensor 5'=427613.0Wh;0.0:0.0;0.0:0.0;; 'Sensor 6'=49.9Hz;0.0:0.0;0.0:0.0;;
4.173 A: normal
229.0 V: normal
818.0 W: normal
956.0 VA: normal
0.86 : normal
427613.0 Wh: normal
49.9 Hz: normal

The problem is now to get it in Graphite. There is only the 0.86 shown. All the others are not possible to write to Graphite. Seems like this is caused by the Units that are delivered with the Perfdata.
Can this be switched off in a way?

bye, Rico

**Comment by rsmuc** [comment]
A, V, W etc. are not officially allowed UOMs. But pnp4nagios is happy with it.
Maybe I could move the UOMs to the label.

**Comment by crsprsp** [comment]
oh, that would be so nice!

**Comment by haxtibal** [comment]
Icinga2's `GraphiteWriter` actually [validates](https://github.com/Icinga/icinga2/blob/83ad98420a28e1af18145f8bbac5a945881c3a78/lib/base/perfdatavalue.cpp#L82) if a unit is one of the allowed ones (in contrast to Icinga 1 and pnp4nagios), and [ignores](https://github.com/Icinga/icinga2/blob/374dd91deb8cf69931f964c6e9b00206bc1e5be6/lib/perfdata/graphitewriter.cpp#L266) it if not. Moving units to the label as @rsmuc suggests seems straight and clean for now.

It's a pity to loose explicit unit information anyway. Icinga 2 guys are aware of the problem (Icinga/icinga2#6071) and are considering a "new plugin API" as foundation to solve it. If we wanted the units back we should probably contribute there.

**Comment by crsprsp** [comment]
seems to work! very good!!!
