### ISSUE TITLE
unknown - snmpget failed - no data for host xxx  OID: .1.3.6.1.4.1.674.10892.5.4.300.10.1.7.1

### ISSUE THREAD

**Issue by swapper82** [rsmuc/health_monitoring_plugins#17]
Getting errors with the check_snmp_idrac.py on some newer idrac 9 servers.

Seems the problem is specific to some newer firmware version of the idrac.
Not 100% shure thats the issue but cant find any other differences.

Version 3.21.26.22 responds with:
IDRAC-MIB-SMIv2::chassisName.1 = No Such Instance currently exists at this OID

Version 3.15.17.15 responds with:
IDRAC-MIB-SMIv2::chassisName.1 = STRING: "Main System Chassis"

**Comment by rsmuc** [comment]
Hi @swapper82, we currently have similar issues with some of our latest Dell R640 servers. At some of the servers most status tables are empty. But some identical servers with the same firmware do respond. If we find a solution (together with Dell) I will let you know.

**Comment by swapper82** [comment]
Hi 
Any updates on this issue? 
Maybe you have a case nr from Dell on this? (that we can refer to push them to fix it)

**Comment by rsmuc** [comment]
My colleagues were able to fix that issue temporary with resetting the idrac interface twice. We are still investigating if that will finally solve the issue.

**Comment by UrbanDavid** [comment]
Hi,
I have problem too. I have 9 servers Dell.
5 x PowerEdge R630 with idrac 7 firwmare 2.50.50.50
Error message is:
Unknown - No response from device for drive (.1.3.6.1.4.1.674.10892.5.5.1.20.130.4.1.4)

1 x PowerEdge R710 with idrac 6 firwmare 2.92
Unknown - No response from device for oid .1.3.6.1.4.1.674.10892.5.4.300.10.1.9.1

1 x PowerEdge R610 with idrac 6 firwmare 2.92
Unknown - No response from device for oid .1.3.6.1.4.1.674.10892.5.4.300.10.1.9.1

1 x PowerEdge R620 with idrac firwmare  
Unknown - No response from device for temperature sensors (.1.3.6.1.4.1.674.10892.5.4.700.20.1.5)

1 x PowerEdge T630 with idrac 7 firwmare 2.50.50.50
all are working good

**Comment by rsmuc** [comment]
Hi @UrbanDavid,

seems that your R630 do not provide information for the harddrives. Try to use the --no-disks option.
The R620 seems to have no temperature sensors. Try to use --no-temperature.

The oid ".1.3.6.1.4.1.674.10892.5.4.300.10.1.9.1" is the information for the product type. 
For testing purposes you could comment out Line 59 in check_snmp_idrac.py:     

# Device information
#    idrac.add_device_information(helper, sess)

Or you could run an snmpwalk. I never had an Rx10 series here. So it's possible that these servers implement an different MIB.

**Comment by UrbanDavid** [comment]
Hi, Option --no-disk is working.
Servers have only two sdcard for vmware esxi and  1 x sata disk for logs. 

If I  set comment for line 59, i see error: Unknown - No response from device for oid .1.3.6.1.4.1.674.10892.5.2.1.0
But it is old servers, It is not important for me. It is version idrac 6. 

Thank you

**Comment by rsmuc** [comment]
no issues reported anymore -> I close that defect for now
