### ISSUE TITLE
check_moxa.py  - ImportError: No module named snmpSessionBaseClass

### ISSUE THREAD

**Issue by 42bios** [rsmuc/health_monitoring_plugins#19]
Hi,
when i try the check_moxa.py i'm getting the following errors:

>./check_moxa.py -H **192.168.x.x** -p 1

>Traceback (most recent call last):
  File "./check_moxa.py", line 23, in <module>
    from snmpSessionBaseClass import add_snmpv3_options, add_common_options, get_common_options, verify_host
ImportError: No module named snmpSessionBaseClass

**Comment by rsmuc** [comment]
Hi, did you install the Python package with pip?

**Comment by 42bios** [comment]
Hi, nope i used apt-get. Maybe is this the problem?

**Comment by 42bios** [comment]
Ah i forgot to copy "snmpSessionBaseClass.py" to the libexec folder...
