### ISSUE TITLE
check_snmp_ilo4 python error and SNMPv3 problems

### ISSUE THREAD

**Issue by slalomsk8er** [rsmuc/health_monitoring_plugins#20]
check_snmp_ilo4.py produced the following error:

`.local/lib/python2.7/site-packages/health_monitoring_plugins/__init__.py", line 36, in <module>
    class SnmpHelper(pynag.Plugins.PluginHelper, HelperExtension):
TypeError: Error when calling the metaclass bases
    Cannot create a consistent method resolution
order (MRO) for bases HelperExtension, PluginHelper
`
I tried with python2 and 3 and got the same result.

To get the plugin to "work" I had to switch

`class SnmpHelper(pynag.Plugins.PluginHelper, HelperExtension):`

to

`class SnmpHelper(HelperExtension, pynag.Plugins.PluginHelper):`

Now I get the error:

`Unknown - No response from device for oid .1.3.6.1.4.1.232.2.2.4.2.0`

The same connection information with /usr/lib/nagios/plugins/check_snmp results in:

`External command error: snmpget: Authentication failure (incorrect password, community or key)`

So not sure what the iLO administrator has to configure for the plugin to work - we would like to use SNMPv3.

**Comment by rsmuc** [comment]
The first issue is not reproducable for me with Python 2.7.13 on Debian Stretch. (The plugins do currently not support Python 3 yet)

Which python version do you use? (python --version)

I tested the plugin with an iLo4 interface and SNMPv3 and it worked with these parameters:
./check_snmp_ilo4.py -H 172.29.X.X --ps=2 --drives=6 --fan=6 --noSystem -V 3 -U test -A testtest -X testtest -x DES -a MD5 -L authPriv

To set up the SNMPv3 user, go to "Administration -> Management". Here is a short tutorial: https://techexpert.tips/hp-ilo/snmpv3-ilo-interface/

**Comment by slalomsk8er** [comment]
Python 2.7.13 on Debian Stretch as well - how strange.

I don't have direct access to configure the iLO but if will cross check the tutorial withe screen shots I got from the administrator.

**Comment by rsmuc** [comment]
fixed in latest version.
I'm using the pynag version from the debian repository. newer pynag versions are causing that issue.
