### ISSUE TITLE
Escape caracter |

### ISSUE THREAD

**Issue by robsonalexandre** [rsmuc/health_monitoring_plugins#7]
In check_snmp_idrac, the cli result string is:
```OK - User assigned name: Main System Chassis - Typ: PowerEdge R620 - Service tag: 1AB2345 | 'system board inlet temp'=17;;;; 'system board exhaust temp'=28;;;; 'cpu1 temp'=34;;;; 'cpu2 temp'=28;;;; 'ps1 voltage 1'=128;;;; 'ps2 voltage 2'=128;;;;```
and web interface don't show the string after the caracter | .

**Comment by rsmuc** [comment]
Hi robsonalexandre,

that's not a bug, that's a feature :)
The data shown after the | are icinga / nagios performancedata:
https://nagios-plugins.org/doc/guidelines.html#AEN200

The performance data can be used for tools like pnp4nagios to paint graphs etc.
